version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python app.py

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
